### ISSUE TITLE
训练效果问题

### ISSUE THREAD

**Issue by flying-pigeon** [mangonihao/MultiHeadJointEntityRelationExtraction_simple#2]
目前在DuIE上用代码跑了，跑了28轮，到后面验证集上的准确率和f1值反而会下降，整体看来验证集上的效果波动比较大，请问这是正常现象吗

**Comment by lvhaiqing** [comment]
> 目前在DuIE上用代码跑了，跑了28轮，到后面验证集上的准确率和f1值反而会下降，整体看来验证集上的效果波动比较大，请问这是正常现象吗

请问您在跑代码的时候没有报错吗？？？我遇到了一个问题，
Traceback (most recent call last):
  File "trainer.py", line 407, in <module>
    trainer.train()
  File "trainer.py", line 133, in train
    self.predict_sample()
  File "trainer.py", line 259, in predict_sample
    pred_ner, pred_rel = pred_ner0[x], pred_rel0[x]
IndexError: list index out of range
在训练一轮之后，评估的时候出错了

**Comment by Xie-Minghui** [comment]
> > 目前在DuIE上用代码跑了，跑了28轮，到后面验证集上的准确率和f1值反而会下降，整体看来验证集上的效果波动比较大，请问这是正常现象吗
> 
> 请问您在跑代码的时候没有报错吗？？？我遇到了一个问题， Traceback (most recent call last): File "trainer.py", line 407, in trainer.train() File "trainer.py", line 133, in train self.predict_sample() File "trainer.py", line 259, in predict_sample pred_ner, pred_rel = pred_ner0[x], pred_rel0[x] IndexError: list index out of range 在训练一轮之后，评估的时候出错了

你可以检查一下是不是数据处理出现了问题

**Comment by Xie-Minghui** [comment]
> 目前在DuIE上用代码跑了，跑了28轮，到后面验证集上的准确率和f1值反而会下降，整体看来验证集上的效果波动比较大，请问这是正常现象吗

下降幅度应该不会太大，属于正常波动范围；如果太大，可能你的检查数据处理或者模型代码是不是有问题
